import {
  Controller,
  Get,
  Post,
  Body,
  Patch,
  Param,
  Delete,
  ParseUUIDPipe, // Use ParseIntPipe if your ID is numeric in Prisma schema
  UsePipes,
  ValidationPipe,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import { RolesService } from './roles.service';
import { CreateRoleDto } from './dto/create-role.dto';
import { UpdateRoleDto } from './dto/update-role.dto';
// Import the Role type generated by Prisma
import { Role } from '@prisma/client';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiParam,
  ApiBody,
} from '@nestjs/swagger'; // Optional: For API documentation
import { Public } from 'src/decorators/public.decorator';

@ApiTags('roles') // Optional: Group endpoints in Swagger UI
@Controller('roles')
export class RolesController {
  // Inject the RolesService
  constructor(private readonly rolesService: RolesService) {}

  /**
   * Creates a new role.
   * Applies validation pipe to the incoming body.
   */
  @Post()
  /* @UsePipes(new ValidationPipe({ whitelist: true, forbidNonWhitelisted: true })) // Validate DTO  */
  @ApiOperation({ summary: 'Create a new role' }) // Optional: Swagger description
  @ApiBody({ type: CreateRoleDto }) // Optional: Swagger body definition
  @ApiResponse({
    status: HttpStatus.CREATED,
    description: 'The role has been successfully created.',
    type: Object,
  }) // Use a DTO class for Swagger type, or 'object' if no DTO is available
  @ApiResponse({
    status: HttpStatus.BAD_REQUEST,
    description: 'Invalid input data.',
  })
  @ApiResponse({
    status: HttpStatus.CONFLICT,
    description: 'Role name already exists.',
  })
  async create(@Body() createRoleDto: CreateRoleDto): Promise<Role> {
    // Delegate creation logic to the service
    return this.rolesService.create(createRoleDto);
  }

  /**
   * Retrieves all roles.
   */
  @Public()
  @Get()
  @ApiOperation({ summary: 'Get all roles' }) // Optional: Swagger
  @ApiResponse({
    status: HttpStatus.OK,
    description: 'Returns all roles.',
    type: Object,
  }) // Use Prisma type if swagger plugin configured
  async findAll(): Promise<Role[]> {
    // Delegate fetching logic to the service
    return this.rolesService.findAll();
  }

  /**
   * Retrieves a specific role by its ID.
   * Uses ParseUUIDPipe to validate the ID format (adjust if using numeric IDs).
   */
  @Get(':id')
  @ApiOperation({ summary: 'Get a role by ID' }) // Optional: Swagger
  @ApiParam({
    name: 'id',
    description: 'The UUID of the role to retrieve',
    type: String,
  }) // Optional: Swagger param description (use 'type: Number' if applicable)
  @ApiResponse({
    status: HttpStatus.OK,
    description: 'Returns the specified role.',
    type: 'object',
  }) // Use Prisma type if swagger plugin configured
  @ApiResponse({ status: HttpStatus.NOT_FOUND, description: 'Role not found.' })
  async findOne(
    // Use ParseUUIDPipe (or ParseIntPipe) to validate and potentially transform the ID
    @Param('id', ParseUUIDPipe) id: string,
  ): Promise<Role> {
    // Service handles the NotFoundException
    const role = await this.rolesService.findOne(id);
    return role;
    // Note: The redundant check `if (!role) { throw new NotFoundException(...) }` is removed
    // because the service already throws NotFoundException if the role isn't found.
  }

  /**
   * Updates a specific role by its ID.
   * Applies validation pipe to the incoming body.
   * Uses ParseUUIDPipe for the ID.
   */
  @Patch(':id')
  @UsePipes(new ValidationPipe({ whitelist: true, forbidNonWhitelisted: true })) // Validate DTO
  @ApiOperation({ summary: 'Update a role by ID' }) // Optional: Swagger
  @ApiParam({
    name: 'id',
    description: 'The UUID of the role to update',
    type: String,
  }) // Optional: Swagger
  @ApiBody({ type: UpdateRoleDto }) // Optional: Swagger
  @ApiResponse({
    status: HttpStatus.OK,
    description: 'The role has been successfully updated.',
    type: Object,
  }) // Use Prisma type if swagger plugin configured
  @ApiResponse({
    status: HttpStatus.BAD_REQUEST,
    description: 'Invalid input data.',
  })
  @ApiResponse({ status: HttpStatus.NOT_FOUND, description: 'Role not found.' })
  @ApiResponse({
    status: HttpStatus.CONFLICT,
    description: 'Role name already exists.',
  })
  async update(
    @Param('id', ParseUUIDPipe) id: string,
    @Body() updateRoleDto: UpdateRoleDto,
  ): Promise<Role> {
    // Delegate update logic to the service. The service handles 'not found' and 'conflict'.
    return this.rolesService.update(id, updateRoleDto);
  }

  /**
   * Deletes a specific role by its ID.
   * Uses ParseUUIDPipe for the ID.
   * Returns HTTP 204 No Content on successful deletion.
   */
  @Delete(':id')
  @HttpCode(HttpStatus.NO_CONTENT) // Set standard HTTP status for successful deletion
  @ApiOperation({ summary: 'Delete a role by ID' }) // Optional: Swagger
  @ApiParam({
    name: 'id',
    description: 'The UUID of the role to delete',
    type: String,
  }) // Optional: Swagger
  @ApiResponse({
    status: HttpStatus.NO_CONTENT,
    description: 'The role has been successfully deleted.',
  }) // Optional: Swagger
  @ApiResponse({ status: HttpStatus.NOT_FOUND, description: 'Role not found.' })
  async remove(@Param('id', ParseUUIDPipe) id: string): Promise<void> {
    // Delegate removal logic to the service. The service handles 'not found'.
    await this.rolesService.remove(id);
    // No content is returned on success
  }
}
